[package]
name = "steg"
version = "0.1.0"
authors = ["djhworld"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.12"
flate2 = "1.0.19"
log = "0.4.11"
